suppressMessages({
  library(shiny)
  library(shinythemes)
  #library(apexcharter)
  library(shinyWidgets)
  library(shinyjs)
  #library(RMariaDB)
  # library(DBI)
  # #library(RSQLite)
  # library(odbc)
  # library(DT)
  # library(tidyverse)
  # #library(dbplyr)
  # library(flextable)
  # library(lubridate)
  # #library(pool)
  # library(uuid)
  # library(shinyAce)
  # #library(mailR)
  # library(shinyFiles)
  # library(rmarkdown)
  # library(emayili)
  # library(stringr)
  # library(knitr)
  # library(kableExtra)
  #library(zintr)
  #library(mobi100c)
})